// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bcekruxshfwpcgpdhotl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjZWtydXhzaGZ3cGNncGRob3RsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNDUzMjUsImV4cCI6MjA2NzgyMTMyNX0.3L4jKawGgHmo7mOzh3B6D8uJdcLzvludwkBbHDm40Ps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});